### ISSUE TITLE
DATA_TYPE_TEXT being ignored

### ISSUE THREAD

**Issue by dumshi** [defold/extension-websocket#23]
websocket.send(conn, msg, {type = websocket.DATA_TYPE_TEXT})

HTML5 build ignores DATA TYPE TEXT and sends binary.

*Not a priority as we can decode binary to string.

**Comment by JCash** [comment]
I still have no idea of how to control this.
I've created a ticket in the Emscripten repo for guidance.
https://github.com/emscripten-core/emscripten/issues/12745

**Comment by britzl** [comment]
Solved in the latest release where we switched to the JS WebSocket API
