### ISSUE TITLE
Issue specifying port number on HTML5 build

### ISSUE THREAD

**Issue by endel** [defold/extension-websocket#34]
Hi there 👋

It seems the port number is being ignored on HTML5 builds: 

```typescript
VM26:1 WebSocket connection to 'ws://localhost/4mjOKNgII/hsucYuWL1?sessionId=Dx6e9FMhr' failed: 
```

Wheres the endpoint specified was `localhost:2567` (from https://github.com/colyseus/colyseus-defold example project)

(The connection works well on native builds)

**Comment by JCash** [comment]
Thanks for the report!

@britzl It might be a good idea to try to setup unit tests for this extension.
E:g. using `node` to run the built engine, and run an example towards some test server.

**Comment by britzl** [comment]
I agree. We need to look into that!
