### ISSUE TITLE
Build error due to websocket library

### ISSUE THREAD

**Issue by banool** [defold/extension-websocket#42]
Hi all,

This morning when trying to build my game in defold, I see this error:

```
/websocket/src/websocket.cpp
	Line 617: too few arguments to function call, expected 8, have 7
    dmConnectionPool::Result pool_result = dmConnectionPool::Dial(g_Websocket.m_Pool, conn->m_Url.m_Hostname, conn->m_Url.m_Port, conn->m_SSL, g_Websocket.m_Timeout, &conn->m_Connection, &sr);
                                           ~~~~~~~~~~~~~~~~~~~~~~                                                                                                                             ^
```

I suspect this may have something to do with the most recent commit, daffff4c06d4446563344b0d5ed213f112bb6980.

I made sure to fetch the latest libraries via Project -> Fetch Libraries.

Any ideas on how we can fix this?

Thanks!

**Comment by banool** [comment]
For anyone else stumbling across this right now, the fix is to change the dependency to:
```
https://github.com/defold/extension-websocket/archive/2.2.3.zip
```

**Comment by britzl** [comment]
Or use the latest beta (d.defold.com/beta) and point your build server to https://build-stage.defold.com

**Comment by JCash** [comment]
> Any ideas on how we can fix this?

>For anyone else stumbling across this right now, the fix is to change the dependency to:
https://github.com/defold/extension-websocket/archive/2.2.3.zip

This is in fact the correct fix.
