### ISSUE TITLE
Expose WebSocket close code?

### ISSUE THREAD

**Issue by endel** [defold/extension-websocket#44]
Hi there!

When inspecting `websocket.EVENT_DISCONNECTED` messages, I can see the close code from inside the `"message"` string field. But parsing the code from that string doesn't feel correct.

Is it currently possible to retrieve the WebSocket close code in a different way? If not, it would be great to expose it to the `EVENT_DISCONNECTED` message itself.

## Current behaviour:

```lua
local ws = websocket.connect(endpoint, params, function(self, conn, data)
  if data.event == websocket.EVENT_DISCONNECTED then
    pprint(data)
    -- ...
  end
end)
```

```
DEBUG:SCRIPT: 
{ --[[0x128680d80]]
  event = 1,
  message = "Server closing (4002). Reason: ''"
}
```

## Expected behaviour:

```
DEBUG:SCRIPT: 
{ --[[0x128680d80]]
  event = 1,
  message = "Server closing. Reason: ''",
  code = 4002
}
```

This is coming from [`wslay_callbacks.cpp#L140-L141`](https://github.com/defold/extension-websocket/blob/97cca427d7ca178ff0206a38a7324305540b7cd2/websocket/src/wslay_callbacks.cpp#L140-L141)

Please let me know if you're interested in supporting this, I can help with a PR! Cheers!

**Comment by endel** [comment]
I was going to parse the string as a workaround (`string.match(data.message, "(%d+)")`), but the `message` comes as empty string on HTML5 builds 😭

```
DEBUG:SCRIPT: 
dmloader.js:507 { --[[0x153dff0]]
dmloader.js:507   message = "",
dmloader.js:507   event = 1
dmloader.js:507 }
```

**Comment by britzl** [comment]
@endel I have prepared a PR for this here: https://github.com/defold/extension-websocket/pull/45

Perhaps you could help me test this?

**Comment by endel** [comment]
Hey @britzl, I hope you are well! :) That was fast! 

I've just tested `Issue-44-close-code` branch and it does work in the editor, but on HTML5 still getting inconsistent results, see:

## Editor build:

```
{ --[[0x12397bc40]]
  event = 1,
  code = 4010,
  message = "Server closing (4010). Reason: ''"
}
```

## HTML5 build:


```
{ --[[0x160ae30]]
dmloader.js:507   message = "",
dmloader.js:507   event = 1,
dmloader.js:507   code = 38114
dmloader.js:507 }
```

(Another try, a different result... 😮)

```
dmloader.js:507 { --[[0x152a2a8]]
dmloader.js:507   message = "",
dmloader.js:507   event = 1,
dmloader.js:507   code = 0
dmloader.js:507 }
```

---

An observation: from the editor, `code = 0` always happens when the server is unreachable, but on HTML5 `code = 0` seems to be always appearing (only once I got the `38114`, not sure why!)

Thanks for taking a look at this!

**Comment by britzl** [comment]
Thanks for testing. I'd like to test HTML5 builds a bit. Do you perhaps have a server URL and some instruction on how I can make the server close the connection?

**Comment by endel** [comment]
Nice, no worries! Sure thing, you can use this locally, `npm install` and `npm start` it 🙏  https://github.com/endel/defold-extension-websocket-issue/tree/master/Server

**Comment by britzl** [comment]
Thanks. I've reworked some of the disconnect handling and the html5 version should now return a close code as well. Please give it a go and let me know if it works as intended.

**Comment by endel** [comment]
Perfect @britzl, thanks for this! 👏  Working as intended!

**Comment by britzl** [comment]
> Perfect @britzl, thanks for this! 👏 Working as intended!

Excellent. I'll create a PR and get it reviewed before merging.
