### ISSUE TITLE
Difference in disconnect behaviour between html5 and desktop

### ISSUE THREAD

**Issue by ainonovo** [defold/extension-websocket#48]
### On html 5 i have this problem. 

**run in editor and (android and windows)**

```
DEBUG:SCRIPT: callback Connected: userdata: 0x0a0be8d0
DEBUG:SCRIPT: callback Receiving: userdata: 0x0a0be8d0 {"status":"success","result":"auth"}
```

**i manual destroy server**

```
ERROR:WEBSOCKET: Websocket poll error: WSLAY_ERR_CALLBACK_FAILURE
DEBUG:SCRIPT: callback Error: 'Websocket closing for 192.168.1.77 (WSLAY_ERR_CALLBACK_FAILURE)'
DEBUG:SCRIPT: callback Disonnected: userdata: 0x0a0be8d0
```

**all works fine,  callback Error and callback Disonnected - fire as well**

**but if i run in browser i have this**

```
DEBUG:SCRIPT: callback Connected: userdata: 0x15c57d8
DEBUG:SCRIPT: callback Receiving: userdata: 0x15c57d8 {"status":"success","result":"auth"}
```

**i manual destroy server**

`DEBUG:SCRIPT: callback Disonnected: userdata: 0x15c57d8`

**where my callback Error - his not fire (((**

**Comment by britzl** [comment]
Split into two reported issues. Second one here: https://github.com/defold/extension-websocket/issues/47

**Comment by britzl** [comment]
@ainonovo if I understand the report correctly you are not getting the `callback Error: 'Websocket closing for 192.168.1.77 (WSLAY_ERR_CALLBACK_FAILURE)'` in HTML5 builds?

If this is the issue you are having I am honestly not surprised. The HTML5 version of the extension uses WebSocket solution from JavaScript. The other platforms uses WSlay websocket implementation. There will be differences. But as far as I can tell you are getting a Disconnect callback in both cases right?

**Comment by ainonovo** [comment]
yes, but I need to catch the error too.

How can I be then? It is very important

since error and shutdown are different things

**Comment by britzl** [comment]
> yes, but I need to catch the error too.

Why? Is it an error? Also, it doesn't seem like it is considered an error by the JavaScript WebSocket implementation. This is reasonable. If the server shuts down it should generate a Disconnect. I would say that the Error is more problematic to be honest.

**Comment by ainonovo** [comment]
but other platforms are ok

maybe i use

```
if html5 then
  navigate.show_popup({content = 'Server terminated the connection unexpectedly. ' .. 
  'If this error occurs too often<br/><br/>Please write to support'}, 'arena_index')
end
```
but I don't like this solution. I write to the user about a specific error - not something went wrong

**Comment by britzl** [comment]
> but other platforms are ok

What do you mean by ok? That they generate both Error and Disconnect?

**Comment by ainonovo** [comment]
the fact that on android and windows I get the text of a specific error, but not in the browser

so a socket error and shutdown are two different things

```
	if data.event == websocket.EVENT_DISCONNECTED then
		if global_.app_debug_ then pprint("callback Disonnected: " .. tostring(conn) .. data.message) end
	elseif data.event == websocket.EVENT_ERROR then
		if global_.app_debug_ then pprint("callback Error: '" .. data.message .. "'") end
       end
```

**Comment by britzl** [comment]
I understand that on HTML5 builds no Error event is generated when the server is shutdown. You only get a Disconnect event right? And surely it is the Disconnect event that matters? I don't think I fully understand the problem.

**Comment by ainonovo** [comment]
error event i got not only from disconnect

I can get errors without disconnecting ))

**Comment by britzl** [comment]
Ok, sure, but I don't think I fully understand the problem you are trying to solve. What is not working as expected? How is the difference in events (ie the missing Error event when disconnecting in HTML5) impacting your game?

**Comment by ainonovo** [comment]
ok, I'll try to explain

I use both http.request and websocket only where needed. The game is not permanently connected to the server unnecessarily

At a certain point, the player can both connect and disconnect from the server.

In case of failure from the server side - I show an error and not a disconnection from the server - since an error occurs when disconnecting

But in principle I already solved the problem for html5

p/s

it's just that on some platforms there is an error, but not in html5. That's the problem

**Comment by britzl** [comment]
Ok, I understand, but we can't guarantee that there will be an exact 1:1 mapping between html5 builds and the desktop implementations. We can't even guarantee that it works the same between different browsers.

**Comment by ainonovo** [comment]
in general, I chose defold because of the presence of a multiplatform. I understand the differences - but it's nice that there is the possibility of changing the code depending on the OS.

But to be honest, it's very difficult. And I'm already working 14 month. I plan to finish at 36 months, but this is not certain))

Thank you for your help
