### ISSUE TITLE
Feature request: "protocol" parameter for connections

### ISSUE THREAD

**Issue by GriffinSego** [defold/extension-websocket#5]
Respected author,

It would be very nice to have support of websocket connection protocols (wsprotocol, req.requestedProtocols[0] in nodeJS)
This feature existed in the original "defold-websocket" extension as the second parameter to `ws:connect()`.
I have created this here because [britzl told me to](https://forum.defold.com/t/defold-docs-problem-how-does-one-use-the-defold-extension-websocket-extension-params/66363/4?u=grify), although I am only mostly certain that I am in the right place.

Thanks,
grify

**Comment by britzl** [comment]
Thanks @Grify. We'll try to address this issue as soon as we can. Or if someone else from the community would like to contribute a Pull Request ofcourse!
