### ISSUE TITLE
Is this kind of a wrong calculation?

### ISSUE THREAD

**Issue by baochungit** [defold/extension-websocket#53]
https://github.com/defold/extension-websocket/blob/65b9e38850740924f91403401d3e155d52142a12/websocket/src/websocket.cpp#L306

Since both `dmTime::GetTime()` and `timeout` parameter are in microseconds, I don't get reason why we should multify with 1000 here

**Comment by JCash** [comment]
Where did you read that `timeout` is in microseconds?
The calcualation suggests it is in milliseconds, and the [documentation confirms it](https://github.com/defold/extension-websocket/blob/65b9e38850740924f91403401d3e155d52142a12/websocket/api/api.script_api#L20-L22).

**Comment by baochungit** [comment]
Sorry, my bad :D
